# Generated by Django 5.2.3 on 2025-06-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/')),
                ('description', models.CharField(max_length=255)),
                ('todays_offer', models.BooleanField(default=False)),
                ('todays_offer_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
